/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoge_org_jni_Example */

#ifndef _Included_com_xiaoge_org_jni_Example
#define _Included_com_xiaoge_org_jni_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoge_org_jni_Example
 * Method:    smart_point
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaoge_org_jni_Example_smart_1point
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaoge_org_jni_Example
 * Method:    mutli_thread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaoge_org_jni_Example_mutli_1thread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
