/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sogou_speech_pingan_abi_test_ABITest */

#ifndef _Included_com_sogou_speech_pingan_abi_test_ABITest
#define _Included_com_sogou_speech_pingan_abi_test_ABITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sogou_speech_pingan_abi_test_ABITest
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint

JNICALL Java_com_sogou_speech_pingan_abi_1test_ABITest_init
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
